version: '3'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      # POSTGRES_DB: mydatabase
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
    ports:
        # Swapping the port because of my Hasura install.
        - "6543:5432"
  # app:
  #   build:
  #     context: .
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db/mydatabase
  #     SPRING_DATASOURCE_USERNAME: myuser
  #     SPRING_DATASOURCE_PASSWORD: mypassword
  #   depends_on:
  #     - postgres
