
spring:
  config:
    activate:
      on-profile: dev
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:6543/wcageval
    username: demouser
    password: demopass
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hiberate:
      # Automatically update table schema to match entities.
      ddl-auto: update

wcageval:
  openai:
    token: ${OPENAI_ACCESS_TOKEN:``}

server:
  port: 8088

name: Development
environment: dev
enabled: false

---

spring:
  config:
    activate:
      on-profile: prod

  graphql:
    graphiql:
      enabled: false


name: Production
enabled: true
